In [1]:
import numpy as np 

In [2]:
A = np.array([[56.0, 0.0, 4.4, 68.0], 
            [1.2, 104.0,52.0,8.0],
            [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [3]:
cal = A.sum(axis=0)

In [4]:
print(cal)

[ 59.  239.  155.4  76.9]


In [6]:
percentage = 100*A/cal.reshape(1,4)
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


In [8]:
a=np.random.randn(5)
print(a)

[ 0.11964173 -1.95624272  0.44590665 -0.3581392   0.47047694]


In [9]:
print(a.shape)

(5,)


In [10]:
print(a.T)

[ 0.11964173 -1.95624272  0.44590665 -0.3581392   0.47047694]


In [11]:
print(np.dot(a,a.T))

4.389644701291307


In [13]:
a=np.random.randn(5,1)

In [14]:
print(a)

[[-1.36097134]
 [-0.82850223]
 [-0.10268709]
 [ 0.26270694]
 [ 0.0271793 ]]


In [15]:
print(a.T)

[[-1.36097134 -0.82850223 -0.10268709  0.26270694  0.0271793 ]]


In [17]:
a=np.random.rand(5)

In [18]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b

In [19]:
print(c)

[[ 0.11110726 -0.03720896  0.03110449]
 [ 0.00919244  0.36769784  0.36006048]
 [-0.0729361   0.26948946 -0.03655086]]


In [20]:
a = np.random.randn(4, 3) # a.shape = (4, 3)
b = np.random.randn(3, 2) # b.shape = (3, 2)
c = a*b

ValueError: operands could not be broadcast together with shapes (4,3) (3,2) 